language: node_js
node_js:
  - "9.7.1"
sudo: false
before_install:
  #install mocha 
  - "npm install --global mocha"
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  - "npm test"
